# Course Notes
## Jupyter Lab Overview

Start Jupyter Lab

- client server architecture
- browser connects to server
- kernels execute commands
- different kernels available
- terminals, text editor, notebook


You can arrange panels as you like them.


In [4]:
pwd

'/home/jet08013/GitHub/Carpentries/2020-01-13/notes'

![Jupyter Image](../png/example.png)


Notebook blends text (markdown) and code (python, in our case)
- click in a box to activate it
- **esc** gives you access to the notebook commands (menu, etc)
- **m** makes a book markdown, **y** makes it code -- or use the menu at the top

## Simple Markdown
- for lists
- lists
- list items with hypen


*emphasis*
**bold**

[links](http://www.nytimes.com)

## Latex

For those who know TeX, the notebook can render math:

$$\sum_{i=1}^{\infty}\frac{1}{n^2} = \frac{\pi^2}{6}$$

# Python

Python is an interpreted language and the blocks of the notebook can be used as a calculator (a fancy one!)

### Variables

In [9]:
name = "Jeremy"
age = 60
probability = .35

In [10]:
print(name, age, probability)

Jeremy 60 0.35


In [11]:
print(name, 'is', age,'years old with probability',probability)

Jeremy is 60 years old with probability 0.35


Variables must be created before being used, by having a value assigned to them.

In [12]:
temperature

50

In [7]:
temperature=50

In [13]:
temperature*2

100

In [14]:
print("the temperature is:", temperature)

the temperature is: 50


In [15]:
full_name = "Jeremy Teitelbaum"

In [16]:
full_name[3]

'e'

**In python, indexing starts from zero!!!**

In [17]:
full_name[0]

'J'

In [18]:
len(full_name)

17

### Types
- strings 
- integers
- floats
- lists

In [25]:
a=123
b='123'

In [26]:
a[1]

TypeError: 'int' object is not subscriptable

In [27]:
b[1]

'2'

In [512]:
L = ['jeremy', 'kendra', 'parkisheet']

In [513]:
L[0]

'jeremy'

### Slicing Strings and lists

In [19]:
full_name[1:3]

'er'

In [20]:
full_name[5:]

'y Teitelbaum'

In [21]:
full_name[:5]

'Jerem'

In [22]:
full_name[3:5:3]

'e'

In [23]:
full_name[:-1]

'Jeremy Teitelbau'

In [24]:
full_name[-1]

'm'

In [28]:
full_name[-1::-1]

'muabletieT ymereJ'

In [514]:
L = ['a','b','c','d']

In [515]:
L[1:3]

['b', 'c']

In [516]:
L[-1]

'd'

In [517]:
L[::2]

['a', 'c']

In [29]:
magic_word = "thanos_must_die"

- What command will determine how many letters are in the ```magic_word```?
- How would you print the fifth through eighth letters of the magic word (inclusive)?

In [31]:
print(magic_word[4:8])
print(magic_word[7:])
print(magic_word[:3])
print(magic_word[:])
print(magic_word[2:-3])
print(magic_word[-3:2:-1])
print(magic_word[0:100])

os_m
must_die
tha
thanos_must_die
anos_must_
d_tsum_son
thanos_must_die


## Types

In python, every variable has a type, but the language figures out the appropriate type by itself.

The most important types are: 
- strings
- integers
- floating point


In [32]:
x="this is a string"
a=137.50
b=12e-1
c=133

In [33]:
print(a)

137.5


In [34]:
print(b)

1.2


In [35]:
print(c)

133


In [37]:
type(a)

float

In [38]:
type(b)

float

In [39]:
type(c)

int

In [40]:
type(x)

str

## Operations on numbers and strings

They're what you'd expect, with some caveats.


In [44]:
x=3.5
y=x/5
z=x*22.4
w=x*1e-1
print("x=",x,"y=",y,"z=",z,"w=",w)

x= 3.5 y= 0.7 z= 78.39999999999999 w= 0.35000000000000003


String addition is concatenation.

In [45]:
x="Jeremy"+"Teitelbaum"

In [46]:
print(x)

JeremyTeitelbaum


Mixing floats and integers is ok (you get a float) but mixing strings and numbers is a problem.

In [50]:
1+3.5

4.5

In [51]:
"Jeremy"+3

TypeError: can only concatenate str (not "int") to str

You can convert floats or ints to strings and then combine them:

In [55]:
"Jeremy Teitelbaum is "+60+" years old"

TypeError: can only concatenate str (not "int") to str

In [56]:
"Jeremy Teitelbaum is "+str(60)+" years old"

'Jeremy Teitelbaum is 60 years old'

In [58]:
3*"a"

'aaa'

In [59]:
type("hello")

str

In [60]:
type(60)

int

In [61]:
type(3.6)

float

In [62]:
len("Jeremy")

6

In [63]:
len(3.5)

TypeError: object of type 'float' has no len()

### Operations on lists

In [518]:
L = ['jeremy','kendra', 'pariksheet','dyanna']

In [519]:
S = ['mouse', 'cat']

In [520]:
L+S

['jeremy', 'kendra', 'pariksheet', 'dyanna', 'mouse', 'cat']

In [521]:
sorted(L)

['dyanna', 'jeremy', 'kendra', 'pariksheet']

In [526]:
['a']*3

['a', 'a', 'a']

In [525]:
L = L + ['x']
print(L)

['jeremy', 'kendra', 'pariksheet', 'dyanna', 'x', 'x', 'x']


### strings to lists and back

In [549]:
list('abcdefg')

['a', 'b', 'c', 'd', 'e', 'f', 'g']

In [551]:
''.join(['a','b','c'])

'abc'

# Comments

In [64]:
# this goes in a code cell, but doesn't get executed

## Built-in Functions

# f(x,y,z) returns a value
- len
- int, str, float
- print
- max
- min
- round
- **help** - function or shift-Tab

In [66]:
round(3.12131,3)

3.121

In [71]:
max('hello')

'o'

In [72]:
min("hello")

'e'

In [73]:
round("hello")

TypeError: type str doesn't define __round__ method

In [74]:
1/2

0.5

In [75]:
result = 60

In [77]:
report = "the result is "+str(result)

In [78]:
print(report)

the result is 60


In [465]:
#help(type)

In [80]:
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



In [81]:
round(123,-2)

100

In [82]:
round(1351,-1)

1350

In [466]:
#help()

In [467]:
report = "Now is the time to flee'

SyntaxError: EOL while scanning string literal (<ipython-input-467-51897dfb7c04>, line 1)

In [468]:
1/0

ZeroDivisionError: division by zero

In [469]:
y = 15-23
x = y+8
z= 3/x

ZeroDivisionError: division by zero

In [470]:
max()

TypeError: max expected 1 arguments, got 0

In [471]:
min()

TypeError: min expected 1 arguments, got 0

# First Break (~90 minutes from start)

## Libraries
### Python is a very simple language

- There are only 33 "keywords" in the python language
```python
False, class, finally, is, return, None, continue, for, lambda, try, True, def, from, nonlocal, while, and, del, global, not, with, as, elif, if, or, yield, assert, else, import, pass, break, except, in, raise
```

All of the interesting capabilities of the language come from extensions to the basic language; these extensions are called "libraries" or "modules".

The language also includes about 100 built-in  functions.  The functions 
```python
int, len, print, str, type, max, min
```
are built-in library.   The built-in functions are very primitive.

To get access to more interesting functions, you need to 
```python
import
```
them by importing the library that defines them.  Many interesting capabilities are added by the [standard library](https://docs.python.org/3/library/)

### Two important libraries 
- numpy
- pandas


In [529]:
import numpy
import pandas


In [531]:
print('pi is ',numpy.pi)

pi is  3.141592653589793


In [532]:
print('e is ',numpy.exp(1))

e is  2.718281828459045


Notice that we refer to the function exp, for example, by first naming the library it came from.

In [533]:
exp(1)

2.718281828459045

In [94]:
math.exp(1)

2.718281828459045

You can get help on a library/module using the help command.

The import command also allows you to adopt abbreviations.


In [2]:
import numpy as np

In [535]:
np.exp(1)

2.718281828459045

In [536]:
from numpy import exp

In [537]:
exp(1)

2.718281828459045

In [538]:
import numpy.random

In [543]:
numpy.random.choice([1,2,3,4,5])

3

In [554]:
np.random.choice(list('ACTTGCTTGAC'))

'T'

In [556]:
import math 
import random
bases = "ACTTGCTTGAC" 
n_bases = len(bases)
idx = np.random.randint(n_bases)
print("random base", bases[idx], "base index", idx)

random base C base index 10


- Data frames are "like" spreadsheets
    - Columns
    - Index
- manipulation is through "methods"

In [557]:
import numpy.random as rnd

In [560]:
rnd.randint(20)

11

## Optional: Dictionaries

In [283]:
f = {}
f['jeremy']=15
f['kendra']=33
f['marshmallow']=100
f['french_fries']='hello'

In [284]:
f['jeremy']

15

In [285]:
f['french_fries']

'hello'

In [286]:
f[0]

KeyError: 0

In [287]:
f.keys()

dict_keys(['jeremy', 'kendra', 'marshmallow', 'french_fries'])

In [288]:
f.values()

dict_values([15, 33, 100, 'hello'])

In [289]:
a = dict(name=['jeremy','kendra','pariksheet'],gender=['m','f','m'])

In [279]:
a

{'name': ['jeremy', 'kendra', 'pariksheet'], 'gender': ['m', 'f', 'm']}

## Optional: Numpy arrays

In [5]:
x = np.array([.5, .7, .1])
y = np.array([1,2,3])

by default, operations are elementwise and functions are applied to each element.  Linear algebra is certainly available but
we won't discuss that today.

In [8]:
print(x+y,x*y,np.log(x))

[1.5 2.7 3.1] [0.5 1.4 0.3] [-0.69314718 -0.35667494 -2.30258509]


In [9]:
a=np.arange(0,10,.1)
print(a)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1
 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9
 9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]


In [702]:
numpy.cos(a)

array([ 1.        ,  0.99500417,  0.98006658,  0.95533649,  0.92106099,
        0.87758256,  0.82533561,  0.76484219,  0.69670671,  0.62160997,
        0.54030231,  0.45359612,  0.36235775,  0.26749883,  0.16996714,
        0.0707372 , -0.02919952, -0.12884449, -0.22720209, -0.32328957,
       -0.41614684, -0.5048461 , -0.58850112, -0.66627602, -0.73739372,
       -0.80114362, -0.85688875, -0.90407214, -0.94222234, -0.97095817,
       -0.9899925 , -0.99913515, -0.99829478, -0.98747977, -0.96679819,
       -0.93645669, -0.89675842, -0.84810003, -0.79096771, -0.7259323 ,
       -0.65364362, -0.57482395, -0.49026082, -0.40079917, -0.30733287,
       -0.2107958 , -0.11215253, -0.01238866,  0.08749898,  0.18651237,
        0.28366219,  0.37797774,  0.46851667,  0.55437434,  0.63469288,
        0.70866977,  0.77556588,  0.83471278,  0.88551952,  0.92747843,
        0.96017029,  0.98326844,  0.9965421 ,  0.99985864,  0.99318492,
        0.97658763,  0.95023259,  0.91438315,  0.86939749,  0.81

In [703]:
3*a

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8,  2.1,  2.4,  2.7,  3. ,
        3.3,  3.6,  3.9,  4.2,  4.5,  4.8,  5.1,  5.4,  5.7,  6. ,  6.3,
        6.6,  6.9,  7.2,  7.5,  7.8,  8.1,  8.4,  8.7,  9. ,  9.3,  9.6,
        9.9, 10.2, 10.5, 10.8, 11.1, 11.4, 11.7, 12. , 12.3, 12.6, 12.9,
       13.2, 13.5, 13.8, 14.1, 14.4, 14.7, 15. , 15.3, 15.6, 15.9, 16.2,
       16.5, 16.8, 17.1, 17.4, 17.7, 18. , 18.3, 18.6, 18.9, 19.2, 19.5,
       19.8, 20.1, 20.4, 20.7, 21. , 21.3, 21.6, 21.9, 22.2, 22.5, 22.8,
       23.1, 23.4, 23.7, 24. , 24.3, 24.6, 24.9, 25.2, 25.5, 25.8, 26.1,
       26.4, 26.7, 27. , 27.3, 27.6, 27.9, 28.2, 28.5, 28.8, 29.1, 29.4,
       29.7])

In [704]:
a*a

array([0.000e+00, 1.000e-02, 4.000e-02, 9.000e-02, 1.600e-01, 2.500e-01,
       3.600e-01, 4.900e-01, 6.400e-01, 8.100e-01, 1.000e+00, 1.210e+00,
       1.440e+00, 1.690e+00, 1.960e+00, 2.250e+00, 2.560e+00, 2.890e+00,
       3.240e+00, 3.610e+00, 4.000e+00, 4.410e+00, 4.840e+00, 5.290e+00,
       5.760e+00, 6.250e+00, 6.760e+00, 7.290e+00, 7.840e+00, 8.410e+00,
       9.000e+00, 9.610e+00, 1.024e+01, 1.089e+01, 1.156e+01, 1.225e+01,
       1.296e+01, 1.369e+01, 1.444e+01, 1.521e+01, 1.600e+01, 1.681e+01,
       1.764e+01, 1.849e+01, 1.936e+01, 2.025e+01, 2.116e+01, 2.209e+01,
       2.304e+01, 2.401e+01, 2.500e+01, 2.601e+01, 2.704e+01, 2.809e+01,
       2.916e+01, 3.025e+01, 3.136e+01, 3.249e+01, 3.364e+01, 3.481e+01,
       3.600e+01, 3.721e+01, 3.844e+01, 3.969e+01, 4.096e+01, 4.225e+01,
       4.356e+01, 4.489e+01, 4.624e+01, 4.761e+01, 4.900e+01, 5.041e+01,
       5.184e+01, 5.329e+01, 5.476e+01, 5.625e+01, 5.776e+01, 5.929e+01,
       6.084e+01, 6.241e+01, 6.400e+01, 6.561e+01, 